### ISSUE TITLE
is this free software?

### ISSUE THREAD

**Issue by adbenitez** [repsej/TheWayOfTheDodo#1]
hi, there is no LICENSE file, is this project open source?

**Comment by adbenitez** [comment]
or otherwise, are you interested into making it available for webxdc? (mini-games shared in chat, see https://webxdc.org)

**Comment by repsej** [comment]
Thanks for asking.  

No, it is not free software.  

Just added a license file :)

Sorry, but I am not currently interested in making it available for webxdc.

**Comment by adbenitez** [comment]
a pity, thanks for replying :pray:
